# Generated by Django 3.1.5 on 2021-02-20 23:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('text', models.CharField(default=None, max_length=250)),
                ('image', models.ImageField(default=None, upload_to='')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 2, 20, 23, 56, 1, 267585, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.IntegerField(max_length=4)),
            ],
        ),
    ]
